### ISSUE TITLE
Mensaje de un sólo factor

### ISSUE THREAD

**Issue by omarbenites** [reyzaguirre/st4gi#12]
Al correr un factorial de 1 solo factor, sale el siguiente error:

` f1 <- paste0("a", 1:5)`
` st4gi::cr.f("A", list(f1), "rcbd", 3)`
**Error in flevels[[2]] : subscript out of bounds** 

Quizás podría salir un mensaje más específico de que se necesita 2 factores como mínimo.

**Comment by reyzaguirre** [comment]
Si solo hay un factor ya no es factorial. En ese caso usar cr.rcbd o cr.crd.

**Comment by omarbenites** [comment]
Hola Raúl, si te entiendo. Te colocaba ese warning, para que el paquete muestre un mensaje a los usuarios y no salga ese error de subcript out of bounds.

**Comment by reyzaguirre** [comment]
ah, ok, ahora lo implemento.
